# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainform.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(796, 521)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_hi = QtWidgets.QLabel(self.centralwidget)
        self.lbl_hi.setGeometry(QtCore.QRect(260, 0, 251, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.lbl_hi.setFont(font)
        self.lbl_hi.setTextFormat(QtCore.Qt.RichText)
        self.lbl_hi.setObjectName("lbl_hi")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 160, 781, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_spent = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_spent.setObjectName("btn_spent")
        self.horizontalLayout.addWidget(self.btn_spent)
        self.lbl_size = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lbl_size.setText("")
        self.lbl_size.setObjectName("lbl_size")
        self.horizontalLayout.addWidget(self.lbl_size)
        self.btn_received = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_received.setObjectName("btn_received")
        self.horizontalLayout.addWidget(self.btn_received)
        self.lbl_im = QtWidgets.QLabel(self.centralwidget)
        self.lbl_im.setGeometry(QtCore.QRect(210, 240, 341, 241))
        self.lbl_im.setText("")
        self.lbl_im.setPixmap(QtGui.QPixmap("../../Downloads/pi.jpg"))
        self.lbl_im.setObjectName("lbl_im")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 796, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_hi.setText(_translate("MainWindow", "ЗДОРОВОЕ ТЕЛО"))
        self.btn_spent.setText(_translate("MainWindow", "Расчёт потраченных каллорий"))
        self.btn_received.setText(_translate("MainWindow", "Расчёт полученных каллорий"))
