# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainform2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(881, 624)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tbt_main = QtWidgets.QTabWidget(self.centralwidget)
        self.tbt_main.setGeometry(QtCore.QRect(0, 0, 881, 581))
        self.tbt_main.setObjectName("tbt_main")
        self.main = QtWidgets.QWidget()
        self.main.setObjectName("main")
        self.lbl_im = QtWidgets.QLabel(self.main)
        self.lbl_im.setGeometry(QtCore.QRect(280, 210, 341, 241))
        self.lbl_im.setText("")
        self.lbl_im.setPixmap(QtGui.QPixmap("../../Downloads/pi.jpg"))
        self.lbl_im.setObjectName("lbl_im")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.main)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 130, 781, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_spent = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_spent.setObjectName("btn_spent")
        self.horizontalLayout.addWidget(self.btn_spent)
        self.btn_youself = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_youself.setObjectName("btn_youself")
        self.horizontalLayout.addWidget(self.btn_youself)
        self.btn_add = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout.addWidget(self.btn_add)
        self.btn_received = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_received.setObjectName("btn_received")
        self.horizontalLayout.addWidget(self.btn_received)
        self.lbl_hi = QtWidgets.QLabel(self.main)
        self.lbl_hi.setGeometry(QtCore.QRect(330, 0, 251, 131))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.lbl_hi.setFont(font)
        self.lbl_hi.setTextFormat(QtCore.Qt.RichText)
        self.lbl_hi.setObjectName("lbl_hi")
        self.tbt_main.addTab(self.main, "")
        self.info = QtWidgets.QWidget()
        self.info.setObjectName("info")
        self.tableWidget = QtWidgets.QTableWidget(self.info)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 421, 541))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.info)
        self.calendarWidget.setGeometry(QtCore.QRect(430, 0, 421, 321))
        self.calendarWidget.setObjectName("calendarWidget")
        self.tbt_main.addTab(self.info, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 881, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tbt_main.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_spent.setText(_translate("MainWindow", "Расчёт потраченных каллорий"))
        self.btn_youself.setText(_translate("MainWindow", "О себе"))
        self.btn_add.setText(_translate("MainWindow", "Изменить данные"))
        self.btn_received.setText(_translate("MainWindow", "Расчёт полученных каллорий"))
        self.lbl_hi.setText(_translate("MainWindow", "ЗДОРОВОЕ ТЕЛО"))
        self.tbt_main.setTabText(self.tbt_main.indexOf(self.main), _translate("MainWindow", "главная"))
        self.tbt_main.setTabText(self.tbt_main.indexOf(self.info), _translate("MainWindow", "Информация"))
