# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recived.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frm_recieved(object):
    def setupUi(self, frm_recieved):
        frm_recieved.setObjectName("frm_recieved")
        frm_recieved.resize(679, 439)
        self.txt_eat = QtWidgets.QTextEdit(frm_recieved)
        self.txt_eat.setGeometry(QtCore.QRect(120, 0, 241, 31))
        self.txt_eat.setObjectName("txt_eat")
        self.lbl_eat = QtWidgets.QLabel(frm_recieved)
        self.lbl_eat.setGeometry(QtCore.QRect(0, 0, 121, 31))
        self.lbl_eat.setObjectName("lbl_eat")
        self.lbl_gramm = QtWidgets.QLabel(frm_recieved)
        self.lbl_gramm.setGeometry(QtCore.QRect(0, 50, 181, 31))
        self.lbl_gramm.setObjectName("lbl_gramm")
        self.txt_gramm = QtWidgets.QTextEdit(frm_recieved)
        self.txt_gramm.setGeometry(QtCore.QRect(180, 50, 291, 31))
        self.txt_gramm.setObjectName("txt_gramm")
        self.lbl_info = QtWidgets.QLabel(frm_recieved)
        self.lbl_info.setGeometry(QtCore.QRect(190, 80, 281, 31))
        self.lbl_info.setObjectName("lbl_info")
        self.lcd_gramm = QtWidgets.QLCDNumber(frm_recieved)
        self.lcd_gramm.setGeometry(QtCore.QRect(230, 240, 201, 23))
        self.lcd_gramm.setObjectName("lcd_gramm")
        self.lbl_kal_gram = QtWidgets.QLabel(frm_recieved)
        self.lbl_kal_gram.setGeometry(QtCore.QRect(10, 230, 221, 41))
        self.lbl_kal_gram.setObjectName("lbl_kal_gram")
        self.lcd_recived = QtWidgets.QLCDNumber(frm_recieved)
        self.lcd_recived.setGeometry(QtCore.QRect(230, 270, 201, 23))
        self.lcd_recived.setObjectName("lcd_recived")
        self.lbl_recived = QtWidgets.QLabel(frm_recieved)
        self.lbl_recived.setGeometry(QtCore.QRect(10, 270, 221, 21))
        self.lbl_recived.setObjectName("lbl_recived")
        self.btn_calc = QtWidgets.QPushButton(frm_recieved)
        self.btn_calc.setGeometry(QtCore.QRect(500, 40, 111, 41))
        self.btn_calc.setObjectName("btn_calc")
        self.verticalLayoutWidget = QtWidgets.QWidget(frm_recieved)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 110, 160, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.lt_product = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.lt_product.setContentsMargins(0, 0, 0, 0)
        self.lt_product.setObjectName("lt_product")
        self.rbtn_meat = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rbtn_meat.setObjectName("rbtn_meat")
        self.btn_grp_product = QtWidgets.QButtonGroup(frm_recieved)
        self.btn_grp_product.setObjectName("btn_grp_product")
        self.btn_grp_product.addButton(self.rbtn_meat)
        self.lt_product.addWidget(self.rbtn_meat)
        self.rbtn_fish = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rbtn_fish.setObjectName("rbtn_fish")
        self.btn_grp_product.addButton(self.rbtn_fish)
        self.lt_product.addWidget(self.rbtn_fish)
        self.rbtn_milk = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rbtn_milk.setObjectName("rbtn_milk")
        self.btn_grp_product.addButton(self.rbtn_milk)
        self.lt_product.addWidget(self.rbtn_milk)
        self.rbtn_veg = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rbtn_veg.setObjectName("rbtn_veg")
        self.btn_grp_product.addButton(self.rbtn_veg)
        self.lt_product.addWidget(self.rbtn_veg)
        self.lbl_error = QtWidgets.QLabel(frm_recieved)
        self.lbl_error.setGeometry(QtCore.QRect(10, 300, 261, 71))
        self.lbl_error.setText("")
        self.lbl_error.setObjectName("lbl_error")
        self.tbl_info = QtWidgets.QTableWidget(frm_recieved)
        self.tbl_info.setGeometry(QtCore.QRect(440, 170, 221, 251))
        self.tbl_info.setRowCount(1)
        self.tbl_info.setColumnCount(2)
        self.tbl_info.setObjectName("tbl_info")

        self.retranslateUi(frm_recieved)
        QtCore.QMetaObject.connectSlotsByName(frm_recieved)

    def retranslateUi(self, frm_recieved):
        _translate = QtCore.QCoreApplication.translate
        frm_recieved.setWindowTitle(_translate("frm_recieved", "Полученные калории"))
        self.lbl_eat.setText(_translate("frm_recieved", "Название продукта"))
        self.lbl_gramm.setText(_translate("frm_recieved", "Сколько примерно Вы съели(грамм)"))
        self.lbl_info.setText(_translate("frm_recieved", "Если вы не напишете , будет считаться 100гр"))
        self.lbl_kal_gram.setText(_translate("frm_recieved", "Количество каллорий на 100 гр продукта"))
        self.lbl_recived.setText(_translate("frm_recieved", "Полученные каллории"))
        self.btn_calc.setText(_translate("frm_recieved", "Рассчитать"))
        self.rbtn_meat.setText(_translate("frm_recieved", "Мясо"))
        self.rbtn_fish.setText(_translate("frm_recieved", "Морепродукты"))
        self.rbtn_milk.setText(_translate("frm_recieved", "Молочные продукты"))
        self.rbtn_veg.setText(_translate("frm_recieved", "Фрукты и овощи"))
