# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recived.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frm_recieved(object):
    def setupUi(self, frm_recieved):
        frm_recieved.setObjectName("frm_recieved")
        frm_recieved.resize(687, 439)
        self.txt_eat = QtWidgets.QTextEdit(frm_recieved)
        self.txt_eat.setGeometry(QtCore.QRect(120, 0, 241, 31))
        self.txt_eat.setObjectName("txt_eat")
        self.lbl_eat = QtWidgets.QLabel(frm_recieved)
        self.lbl_eat.setGeometry(QtCore.QRect(0, 0, 121, 31))
        self.lbl_eat.setObjectName("lbl_eat")
        self.lbl_gramm = QtWidgets.QLabel(frm_recieved)
        self.lbl_gramm.setGeometry(QtCore.QRect(0, 50, 181, 31))
        self.lbl_gramm.setObjectName("lbl_gramm")
        self.txt_gramm = QtWidgets.QTextEdit(frm_recieved)
        self.txt_gramm.setGeometry(QtCore.QRect(180, 50, 291, 31))
        self.txt_gramm.setObjectName("txt_gramm")
        self.label_3 = QtWidgets.QLabel(frm_recieved)
        self.label_3.setGeometry(QtCore.QRect(190, 80, 281, 31))
        self.label_3.setObjectName("label_3")
        self.lcd_gramm = QtWidgets.QLCDNumber(frm_recieved)
        self.lcd_gramm.setGeometry(QtCore.QRect(220, 140, 201, 23))
        self.lcd_gramm.setObjectName("lcd_gramm")
        self.lbl_kal_gram = QtWidgets.QLabel(frm_recieved)
        self.lbl_kal_gram.setGeometry(QtCore.QRect(0, 130, 221, 41))
        self.lbl_kal_gram.setObjectName("lbl_kal_gram")
        self.lcd_recived = QtWidgets.QLCDNumber(frm_recieved)
        self.lcd_recived.setGeometry(QtCore.QRect(220, 170, 201, 23))
        self.lcd_recived.setObjectName("lcd_recived")
        self.lbl_recived = QtWidgets.QLabel(frm_recieved)
        self.lbl_recived.setGeometry(QtCore.QRect(0, 170, 221, 21))
        self.lbl_recived.setObjectName("lbl_recived")
        self.btn_calc = QtWidgets.QPushButton(frm_recieved)
        self.btn_calc.setGeometry(QtCore.QRect(500, 40, 111, 41))
        self.btn_calc.setObjectName("btn_calc")
        self.lbl_upset = QtWidgets.QLabel(frm_recieved)
        self.lbl_upset.setGeometry(QtCore.QRect(20, 220, 271, 31))
        self.lbl_upset.setObjectName("lbl_upset")
        self.txt_grammup = QtWidgets.QTextEdit(frm_recieved)
        self.txt_grammup.setGeometry(QtCore.QRect(190, 300, 291, 31))
        self.txt_grammup.setObjectName("txt_grammup")
        self.txt_eatup = QtWidgets.QTextEdit(frm_recieved)
        self.txt_eatup.setGeometry(QtCore.QRect(130, 250, 241, 31))
        self.txt_eatup.setObjectName("txt_eatup")
        self.lbl_gramm_2 = QtWidgets.QLabel(frm_recieved)
        self.lbl_gramm_2.setGeometry(QtCore.QRect(10, 300, 181, 31))
        self.lbl_gramm_2.setObjectName("lbl_gramm_2")
        self.lbl_eat_2 = QtWidgets.QLabel(frm_recieved)
        self.lbl_eat_2.setGeometry(QtCore.QRect(10, 250, 121, 31))
        self.lbl_eat_2.setObjectName("lbl_eat_2")
        self.btn_upset = QtWidgets.QPushButton(frm_recieved)
        self.btn_upset.setGeometry(QtCore.QRect(500, 260, 121, 41))
        self.btn_upset.setObjectName("btn_upset")

        self.retranslateUi(frm_recieved)
        QtCore.QMetaObject.connectSlotsByName(frm_recieved)

    def retranslateUi(self, frm_recieved):
        _translate = QtCore.QCoreApplication.translate
        frm_recieved.setWindowTitle(_translate("frm_recieved", "Form"))
        self.lbl_eat.setText(_translate("frm_recieved", "Название блюда"))
        self.lbl_gramm.setText(_translate("frm_recieved", "Сколько примерно Вы съели(грамм)"))
        self.label_3.setText(_translate("frm_recieved", "Если вы не напишете , будет считаться 100гр"))
        self.lbl_kal_gram.setText(_translate("frm_recieved", "Количество каллорий на 100 гр продукта"))
        self.lbl_recived.setText(_translate("frm_recieved", "Полученные каллории"))
        self.btn_calc.setText(_translate("frm_recieved", "Рассчитать"))
        self.lbl_upset.setText(_translate("frm_recieved", "Если нет такого продукта, Вы можете внести его"))
        self.lbl_gramm_2.setText(_translate("frm_recieved", "Каллорий на 100 грамм"))
        self.lbl_eat_2.setText(_translate("frm_recieved", "Название блюда"))
        self.btn_upset.setText(_translate("frm_recieved", "Внести"))
