# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spent.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frm_spent(object):
    def setupUi(self, frm_spent):
        frm_spent.setObjectName("frm_spent")
        frm_spent.resize(680, 505)
        self.txt_gum = QtWidgets.QTextEdit(frm_spent)
        self.txt_gum.setGeometry(QtCore.QRect(90, 0, 421, 31))
        self.txt_gum.setObjectName("txt_gum")
        self.label = QtWidgets.QLabel(frm_spent)
        self.label.setGeometry(QtCore.QRect(0, 10, 121, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(frm_spent)
        self.label_2.setGeometry(QtCore.QRect(0, 50, 141, 21))
        self.label_2.setObjectName("label_2")
        self.txt_time = QtWidgets.QTextEdit(frm_spent)
        self.txt_time.setGeometry(QtCore.QRect(150, 40, 421, 31))
        self.txt_time.setObjectName("txt_time")
        self.btn_spt = QtWidgets.QPushButton(frm_spent)
        self.btn_spt.setGeometry(QtCore.QRect(10, 80, 161, 41))
        self.btn_spt.setObjectName("btn_spt")
        self.label_3 = QtWidgets.QLabel(frm_spent)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 151, 21))
        self.label_3.setObjectName("label_3")
        self.lbl_spt = QtWidgets.QLabel(frm_spent)
        self.lbl_spt.setGeometry(QtCore.QRect(170, 140, 81, 16))
        self.lbl_spt.setText("")
        self.lbl_spt.setObjectName("lbl_spt")
        self.tableView = QtWidgets.QTableView(frm_spent)
        self.tableView.setGeometry(QtCore.QRect(0, 220, 256, 281))
        self.tableView.setObjectName("tableView")
        self.label_4 = QtWidgets.QLabel(frm_spent)
        self.label_4.setGeometry(QtCore.QRect(0, 185, 101, 31))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(frm_spent)
        QtCore.QMetaObject.connectSlotsByName(frm_spent)

    def retranslateUi(self, frm_spent):
        _translate = QtCore.QCoreApplication.translate
        frm_spent.setWindowTitle(_translate("frm_spent", "Form"))
        self.label.setText(_translate("frm_spent", "Вид упражнения:"))
        self.label_2.setText(_translate("frm_spent", "Потраченное время (часов)"))
        self.btn_spt.setText(_translate("frm_spent", "Рассчитать"))
        self.label_3.setText(_translate("frm_spent", "Ваши потраченные каллории:"))
        self.label_4.setText(_translate("frm_spent", "Виды упражнений"))
