# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spent.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frm_spent(object):
    def setupUi(self, frm_spent):
        frm_spent.setObjectName("frm_spent")
        frm_spent.resize(680, 505)
        self.textEdit = QtWidgets.QTextEdit(frm_spent)
        self.textEdit.setGeometry(QtCore.QRect(90, 0, 421, 31))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(frm_spent)
        self.label.setGeometry(QtCore.QRect(0, 10, 121, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(frm_spent)
        self.label_2.setGeometry(QtCore.QRect(0, 50, 141, 21))
        self.label_2.setObjectName("label_2")
        self.textEdit_2 = QtWidgets.QTextEdit(frm_spent)
        self.textEdit_2.setGeometry(QtCore.QRect(150, 40, 421, 31))
        self.textEdit_2.setObjectName("textEdit_2")

        self.retranslateUi(frm_spent)
        QtCore.QMetaObject.connectSlotsByName(frm_spent)

    def retranslateUi(self, frm_spent):
        _translate = QtCore.QCoreApplication.translate
        frm_spent.setWindowTitle(_translate("frm_spent", "Form"))
        self.label.setText(_translate("frm_spent", "Вид упражнения:"))
        self.label_2.setText(_translate("frm_spent", "Потраченное время (мин.)"))
